import { StyleSheet } from "react-native";
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#050505",
    paddingTop: 45, // Más espacio para la barra de estado
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  logoContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  logoRed: {
    color: "#E60023",
    fontSize: 28,
    fontWeight: "900",
  },
  logoWhite: {
    color: "#FFFFFF",
    fontSize: 28,
    fontWeight: "900",
    marginLeft: 5,
  },
  icons: {
    flexDirection: "row",
    gap: 15,
  },
  badge: {
    position: "absolute",
    right: -5,
    top: -5,
    backgroundColor: "#E60023",
    borderRadius: 10,
    width: 18,
    height: 18,
    justifyContent: "center",
    alignItems: "center",
  },
  badgeText: {
    color: "white",
    fontSize: 10,
    fontWeight: "bold",
  },
  storyScroll: {
    paddingLeft: 15,
    marginBottom: 25,
  },
  crearStory: {
    width: 85,
    alignItems: "center",
    marginRight: 18,
  },
  storyCircle: {
    width: 75,
    height: 75,
    borderRadius: 50,
    backgroundColor: "#111",
    borderWidth: 2,
    borderColor: "#E60023",
    justifyContent: "center",
    alignItems: "center",
  },
  storyInitial: {
    color: "#FFFFFF",
    fontSize: 28,
    fontWeight: "bold",
  },
  storyText: {
    color: "white",
    marginTop: 8,
    fontSize: 13,
  },
  storyContainer: {
    alignItems: "center",
    marginRight: 18,
  },
  storyImage: {
    width: 75,
    height: 75,
    borderRadius: 50,
    borderWidth: 3,
    borderColor: "#E60023",
  },
  storyLabel: {
    color: "white",
    marginTop: 8,
    fontSize: 13,
  },
  tabs: {
    paddingHorizontal: 15,
    marginBottom: 20,
    height: 50,
  },
  tabItem: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#1A1A1A",
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 25,
    marginRight: 10,
    borderWidth: 1,
    borderColor: "#333",
    height: 40,
  },
  tabActive: {
    backgroundColor: "#E60023",
    borderColor: "#E60023",
  },
  tabText: {
    color: "#888",
    fontWeight: "bold",
    fontSize: 13,
  },
  tabActiveText: {
    color: "white",
    fontWeight: "bold",
    fontSize: 13,
  },
  post: {
    backgroundColor: "#0D0D0D",
    marginHorizontal: 15,
    borderRadius: 18,
    padding: 18,
    marginBottom: 20,
  },
  postHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 15,
  },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#333",
    justifyContent: "center",
    alignItems: "center",
  },
  avatarText: {
    color: "white",
    fontWeight: "bold",
    fontSize: 16,
  },
  user: {
    color: "white",
    fontSize: 20,
    fontWeight: "bold",
  },
  info: {
    color: "#888",
    marginTop: 3,
  },
  time: {
    color: "#777",
  },
  postText: {
    color: "white",
    fontSize: 18,
    lineHeight: 28,
    marginBottom: 18,
  },
  category: {
    alignSelf: "flex-start",
    paddingHorizontal: 15,
    paddingVertical: 7,
    borderRadius: 20,
    marginBottom: 22,
  },
  categoryText: {
    color: "white",
    fontWeight: "bold",
  },
  actions: {
    flexDirection: "row",
    justifyContent: "space-between",
    borderTopWidth: 1,
    borderTopColor: "#222",
    paddingTop: 12,
  },
  action: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  actionText: {
    color: "white",
    fontSize: 16,
  },
  bottomNav: {
    flexDirection: "row",
    backgroundColor: "#050505",
    borderTopWidth: 1,
    borderTopColor: "#1F1F1F",
    paddingTop: 12,
    paddingHorizontal: 20,
    justifyContent: "space-between",
  },
  navItem: {
    alignItems: "center",
    justifyContent: "center",
    flex: 1,
  },
  navText: {
    color: "#8A8A8A",
    fontSize: 10,
    marginTop: 4,
  },
  navTextActive: {
    color: "#FF4D67",
    fontWeight: "bold",
  },
  smallBadge: {
    position: "absolute",
    right: -6,
    top: -6,
    backgroundColor: "#E60023",
    borderRadius: 8,
    width: 14,
    height: 14,
    justifyContent: "center",
    alignItems: "center",
  },
  smallBadgeText: {
    color: "white",
    fontSize: 8,
    fontWeight: "bold",
  },
  activeLine: {
    position: "absolute",
    top: 0,
    width: 40, // Ancho fijo de la línea
    height: 3,
    backgroundColor: "#E60023",
    borderBottomLeftRadius: 3,
    borderBottomRightRadius: 3,
  },
});
export default styles;
